### ISSUE TITLE
lib/relaton_bib/contributor.rb:150:in `block in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by CAMOBAP** [relaton/relaton-bib#80]
This issue happens for private flavor BSI (https://github.com/metanorma/mn-samples-bsi/actions/runs/6191758202/job/16810620665#step:5:9972)

```
/usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/contributor.rb:150:in `block in to_xml': undefined method `to_xml' for nil:NilClass (NoMethodError)

        organization.to_xml(**opts)
                    ^^^^^^^
Did you mean?  to_yaml
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/contributor.rb:145:in `to_xml'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/person.rb:94:in `block (2 levels) in to_xml'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/person.rb:94:in `each'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/person.rb:94:in `block in to_xml'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/person.rb:92:in `to_xml'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/contribution_info.rb:96:in `to_xml'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:609:in `block (3 levels) in render_xml'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:607:in `block (2 levels) in render_xml'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:606:in `each'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:606:in `block in render_xml'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:433:in `insert'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:415:in `method_missing'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:598:in `render_xml'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:367:in `block in to_xml'
	from /usr/local/bundle/gems/nokogiri-1.14.5-x86_64-linux/lib/nokogiri/xml/builder.rb:331:in `initialize'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:366:in `new'
	from /usr/local/bundle/gems/relaton-bib-1.16.0/lib/relaton_bib/bibliographic_item.rb:366:in `to_xml'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/bibdata.rb:49:in `to_xml'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/bibcollection.rb:72:in `block in to_xml'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/bibcollection.rb:70:in `each'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/bibcollection.rb:70:in `to_xml'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/cli/relaton_file.rb:157:in `concatenate_and_write_to_files'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/cli/relaton_file.rb:19:in `concatenate'
	from /usr/local/bundle/gems/relaton-cli-1.16.0/lib/relaton/cli/relaton_file.rb:58:in `concatenate'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli/site_generator.rb:71:in `build_collection_file'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli/site_generator.rb:34:in `block in generate'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli/site_generator.rb:33:in `chdir'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli/site_generator.rb:33:in `generate'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /usr/local/bundle/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/lib/metanorma/cli.rb:34:in `start'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/exe/metanorma:25:in `block in <top (required)>'
	from /usr/local/bundle/gems/metanorma-cli-1.8.4/exe/metanorma:43:in `<top (required)>'
	from /usr/local/bundle/bin/metanorma:25:in `load'
	from /usr/local/bundle/bin/metanorma:25:in `<main>'
```

**Comment by andrew2net** [comment]
@CAMOBAP The affiliation doesn't have an `organization` argument. The argument is mandatory but Ruby doesn't check if it's `nil`.
I can't get from the log where the date come from. Do you know which document cause the error?
We can rise error when creating an affiliation object if organization is `nil`, but we can't create affiliation without organization.

**Comment by CAMOBAP** [comment]
@andrew2net thanks a lot for the investigation

@opoudjis maybe you can help to:

1. Create the issue in the proper place.
1. Review the proposed fix from @andrew2net, looks reasonable to me, how do you think?

**Comment by CAMOBAP** [comment]
cc @ronaldtse

**Comment by ronaldtse** [comment]
@CAMOBAP the cause of the crash is described here:
* https://github.com/metanorma/mn-samples-bsi/issues/328

**Comment by andrew2net** [comment]
@CAMOBAP I get no any errors with relation-bib v1.16.0. Please try to update Relaton.

**Comment by CAMOBAP** [comment]
> @CAMOBAP I get no any errors with relation-bib v1.16.0. Please try to update Relaton.

According to stack trace it's already 'relaton-bib-1.16.0'

**Comment by andrew2net** [comment]
@CAMOBAP Ah, indeed. Ronald created another issue with this error and in that stack trace it's 1.14.13.
I've pushed a relaton-bib update that raises an error when `affiliation/organization` is incorrect. Could you use the GH version and show me the log?

**Comment by andrew2net** [comment]
@CAMOBAP I've made a relaton-bib update that raises an error if affifiation/organiztion is invalid. Could you use the relaton-bib version 1.14.14 or later and give me the log?

**Comment by CAMOBAP** [comment]
@andrew2net thanks the error message is clear now

```
/usr/local/bundle/gems/relaton-bib-1.16.1/lib/relaton_bib/contributor.rb:137:in `initialize': organization should be an instance of RelatonBib::Organization (ArgumentError)
```

I think we can close this one

**Comment by ronaldtse** [comment]
@CAMOBAP but the underlying issue is not fixed -- we're not supposed to see any error here. Can you reopen?

**Comment by CAMOBAP** [comment]
@ronaldtse as far as I understood the issue is in the mn-samples-bsi, isn't it? And as far as I see we have dedicated issue for it https://github.com/metanorma/mn-samples-bsi/issues/328

**Comment by ronaldtse** [comment]
Ah you're right. This problem is actually in Metanorma-BSI. Closing.
